
all:
	g++ ./vector.cpp -g -O0 -o vector
	echo "--------- vector -----------"
	./vector
	g++ ./deque.cpp -g -O0 -o deque
	echo "--------- deque -----------"
	./deque
	g++ ./set.cpp -g -O0 -o set
	echo "--------- set -----------"
	./set
	g++ ./map.cpp -g -O0 -o map 
	echo "--------- map -----------"
	./map

clean:
	rm -f vector deque set map

