
all:
	g++ ./02-vector.cpp -g -O0 -o vector
	echo "--------- vector -----------"
	./vector
	g++ ./01-deque.cpp -g -O0 -o deque
	echo "--------- deque -----------"
	./deque
	g++ ./03-set.cpp -g -O0 -o set
	echo "--------- set -----------"
	./set
	g++ ./04-map.cpp -g -O0 -o map 
	echo "--------- map -----------"
	./map

clean:
	rm -f vector deque set map

