
all:
	g++ ./05-deleter.cpp -o 05-deleter -g -O0 -std=c++11
	./05-deleter

#	g++ ./04-std-ptr-ref.cpp -o 04-std-ptr-ref -g -O0 -std=c++11
#	./04-std-ptr-ref
#	g++ ./03-sptr-ref.cpp -o 03-sptr-ref -g -O0 -std=c++11
#	./03-sptr-ref
#	g++ ./01-sptr.cpp -o 01-sptr -g -O0 -std=c++11
#	g++ ./02-std-ptr.cpp -o 02-std-ptr -g -O0 -std=c++11
#	./01-sptr
#	./02-std-ptr


clean:
	rm -f 01-sptr 02-std-ptr 03-sptr-ref 04-std-ptr-ref
