all:
	g++ ./01-lambda.cpp -g -O0 -o 01-lambda
	g++ ./02-模板特例化.cpp -g -O0 -o 02
	g++ ./03-functional.cpp -g -O0 -o 03
	g++ ./04-bind.cpp -g -O0 -o 04
	g++ ./05-实际应用示例.cpp -g -O0 -o 05
	./01-lambda
	./02
	./03
	./04
	./05

clean:
	rm -f ./01-lambda ./02 ./03 04 05
